name: "Dynamic Application Security Testing (DAST) with Nuclei"
description: "Nuclei is an open-source web application security scanner developed by ProjectDiscovery.io."
branding:
  icon: "alert-circle"
  color: "purple"

inputs:
  urls-txt:
    description: "List of urls to run templates"
    required: true
    default: "nuclei.txt"
  custom-templates:
    description: "Custom templates to check on urls"
    required: false
    default: "custom-templates/"
  user-agent:
    description: "Set a User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/projectdiscovery/nuclei.git
        cd nuclei/v2/cmd/nuclei
        go build
        echo "${{ github.workspace }}/nuclei/v2/cmd/nuclei" >> $GITHUB_PATH
      shell: bash

    - run: |
        nuclei -l ${{ inputs.urls-txt }} \
          -json \
          -silent \
          -update-directory . \
          -update-templates \
          -t nuclei-templates/ \
          -t ${{ inputs.custom-templates }} \
          -H "User-Agent:${{ inputs.user-agent }}" \
          -o nuclei.log
      shell: bash
