name: "Nuclei Action"
description: "Nuclei is a fast and customisable vulnerability scanner based on simple YAML based DSL"

inputs:
  target:
    description: "Target to run nuclei scan"
    required: true
  urls:
    description: "List of urls to run templates"
    required: false
    default: "urls.txt"
  templates:
    description: "Templates input file/files to check across hosts"
    required: false
  output:
    description: "File to save output result"
    required: false
    default: "nuclei.log"
  json:
    description: "Write nuclei output in JSON format"
    required: false
    default: false
  include-rr:
    description: "Write requests/responses for matches in JSON output"
    required: false
    default: false
  config:
    description: "Nuclei configuration file"
    required: false
  user-agent:
    description: "Set a Custom User-Agent header"
    required: false
  github-report:
    description: "Active Nuclei Reporting Module for Github"
    required: false
    default: false
  jira-report:
    description: "Active Nuclei Reporting Module for Jira"
    required: false
    default: false
  github-token:
    description: "Github token for create issues"
    required: false
    
runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/nuclei ] && GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash
    - run: |
        [ ! -z ${{ inputs.config }} ] && cp ${{ inputs.config }} /.config/nuclei/config.yaml
        [ ! -z "${{ inputs.user-agent }}" ] && echo 'useragent=-H "User-Agent: ${{ inputs.user-agent }}"' >> $GITHUB_ENV
        ${{ inputs.include-rr }} && echo "includerr=-irr" >> $GITHUB_ENV
        ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
        ${{ inputs.target }} && echo "target=-target" >> $GITHUB_ENV

        ${{ inputs.github-report }} \
        && touch ~/nuclei-github-config.yaml \
        && echo -e "github:" >> ~/nuclei-github-config.yaml \
        && echo -e "  username: \"$GITHUB_ACTOR\"" >> ~/nuclei-github-config.yaml \
        && echo -e "  owner: \"${GITHUB_REPOSITORY%%/*}\"" >> ~/nuclei-github-config.yaml \
        && echo -e "  token: \"${{ inputs.github-token }}\"" >> ~/nuclei-github-config.yaml \
        && echo -e "  project-name: \"${GITHUB_REPOSITORY#*/}\"" >> ~/nuclei-github-config.yaml \
        && echo -e "  issue-label: \"Nuclei Reporting\"" >> ~/nuclei-github-config.yaml \
        && echo "githubconfig=-rc ~/nuclei-github-config.yaml" >> $GITHUB_ENV
        
        nuclei \
          -update-templates \
          -update-directory ./nuclei-templates
      shell: bash
    - run: |
        
        nuclei \
          -l ${{ inputs.target }} \
          -l ${{ inputs.urls }} \
          -t ./nuclei-templates/${{ inputs.templates }} \
          ${{ env.useragent }} \
          -o ${{ inputs.output }} \
          ${{ env.json }} \
          ${{ env.githubconfig }} \
          ${{ env.includerr }}
      shell: bash
