name: "Nuclei Action"
description: "Nuclei is a fast tool for configurable targeted scanning based on templates offering massive extensibility and ease of use."
branding:
  icon: "alert-circle"
  color: "purple"

inputs:
  urls:
    description: "List of urls to run templates"
    required: true
    default: "urls.txt"
  templates:
    description: "Templates input file/files to check across hosts"
    required: false
    default: "./nuclei-templates/"
  output:
    description: "File to save output result"
    required: false
    default: "output.txt"
  user-agent:
    description: "Set a User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/projectdiscovery/nuclei.git
        cd nuclei/v2/cmd/nuclei/
        go build
        echo "${{ github.workspace }}/nuclei/v2/cmd/nuclei" >> $GITHUB_PATH
      shell: bash

    - run: |
        nuclei \
          -l ${{ inputs.urls }} \
          -t ${{ inputs.templates }} \
          -o ${{ inputs.output }} \
          -json \
          -include-rr \
          -update-templates \
          -update-directory ./ \
          -H "User-Agent: ${{ inputs.user-agent }}"
      shell: bash
